# Generated by Django 2.2.7 on 2020-01-04 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
